AmdShop/Areas/Admin/Controllers/CompanyController.cs
using Ecom.DataAccess.Repository.IRepository;
using Ecom.Models.Models;
using Ecom.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CompanyController(IUnitOfWork unitOfWorke, IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
            _unitOfWork = unitOfWorke;
        }
        public IActionResult Index()
        {
            //   List<Company> companys = _unitOfWork.Company.GetAll().ToList();
            return View();
        }

        public async Task<IActionResult> Upsert(Guid? id)
        {

            if (id == null)
            {//create
                return View(new Company());
            }
            else
            {//update
                Company company = await _unitOfWork.Company.Get(u => u.Id == id);
                return View(company);
            }
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Upsert(Company company)
        {

            if (ModelState.IsValid)
            {

                if (company.Id == Guid.Empty)
                {
                    _unitOfWork.Company.Add(company);
                    TempData["success"] = "Company Added Suceessful";

                }
                else
                {
                    _unitOfWork.Company.Update(company);
                    TempData["success"] = "Company Updated Suceessful";

                }
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            else
            {

                return View(company);
            }

        }


        #region API CALLS
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            List<Company> Companys = (await _unitOfWork.Company.GetAll()).ToList();
            return Json(new { data = Companys });
        }

        [ValidateAntiForgeryToken]
        [HttpDelete]
        public async Task<IActionResult> Delete(Guid? id)
        {
            var CompanyToDelete = await _unitOfWork.Company.Get(u => u.Id == id);
            if (CompanyToDelete == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Company.Remove(CompanyToDelete);
            _unitOfWork.Save();


            return Json(new { success = true, message = "Delete successful" });
        }
        #endregion

    }
}

AmdShop/Areas/Admin/Views/Company/Index.cshtml
<div class="card shadow border-0 my-4" >
    <div class="card-header bg-primary  ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h4 class="text-white py-2">Company List</h4>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end"> 
                <a asp-controller="Company" asp-action="Upsert" class="btn btn-primary hover ">
                    <i class="bi bi-plus-circle"></i>  Create Company
                </a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped" >
            <thead>
                <tr >
                    <th class="headtable bg-primary text-white bg-gradient"> Name </th>       
                    <th class="headtable bg-primary text-white bg-gradient"> Address </th>
                    <th class="headtable bg-primary text-white bg-gradient"> City </th>
                    <th class="headtable bg-primary text-white bg-gradient"> State </th>
                    <th class="headtable bg-primary text-white bg-gradient"> Phone Number </th>
                    <th class="headtable bg-primary text-white bg-gradient"></th>

                </tr>  
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/company.js"></script>
}

AmdShop/Areas/Admin/Views/Company/Upsert.cshtml
@model Company
<div class="row">
    <div class="card shadow border-0 my-4 col-10 offset-2  col-md-8 offset-md-2 col-lg-6 offset-lg-3 " style="max-width:70%">
        <div class="card-header bg-primary bg-gradient ml-0 py-3">
            <div class="row">
                <div class="col-12 text-center">
                    <h2 class="text-white py-2"> @(Model.Id != Guid.Empty ? "Update" : "Create") Company</h2>
                </div>
            </div> 
        </div>
        <div class="card-body p-4">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="Id" hidden />        
                <div class="row"> 
                    <div class="col-12">
                        <div class="border p-3 mt-4">
                            <div class="mb-3 row p-1">
                                <label asp-for="Name" class="p-0 "></label>
                                <input asp-for="Name" type="text" class="form-control " />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                           
                            <div class="mb-3 row p-1">
                                <label asp-for="PhoneNumber" class="p-0 "></label>
                                <input asp-for="PhoneNumber" type="text" class="form-control " />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                            <div class="mb-3 row p-1">
                                <label asp-for="StreetAddress" class="p-0 "></label>
                                <input asp-for="StreetAddress" type="text" class="form-control " />
                                <span asp-validation-for="StreetAddress" class="text-danger"></span>
                            </div>                        
                            <div class="mb-3 row p-1">
                                <label asp-for="City" class="p-0 "></label>
                                <input asp-for="City" type="text" class="form-control " />
                                <span asp-validation-for="City" class="text-danger"></span>
                            </div>
                            <div class="mb-3 row p-1">
                                <label asp-for="State" class="p-0 "></label>
                                <input asp-for="State" type="text" class="form-control " />
                                <span asp-validation-for="State" class="text-danger"></span>
                            </div>
                            <div class="mb-3 row p-1">
                                <label asp-for="PostalCode" class="p-0 "></label>
                                <input asp-for="PostalCode" type="number" class="form-control " />
                                <span asp-validation-for="PostalCode" class="text-danger"></span>
                            </div>
                           
                            <div class="row">
                                <div class="col-12  col-sm-5  m-2 ">
                                    @if (Model.Id != Guid.Empty)
                                    {
                                        <button type="submit" class="btn btn-primary hover  " style="width:120px">
                                            <i class="fa-solid fa-pen-to-square"></i>
                                            <span class="text">Update   </span>
                                        </button>
                                    }
                                    else
                                    {
                                        <button type="submit" class="btn btn-primary hover  " style="width:120px">
                                            <i class="fa fa-plus-square"></i>
                                            <span class="text">Create   </span>
                                        </button>
                                    }

                                </div>
                                <div class="col-12   col-md-3 m-2 ">
                                    <button asp-controller="Company" asp-action="Index" class="btn btn-secondary border-black border-1   hover" style="width:120px" formnovalidate>
                                        <i class="fas fa-arrow-left"></i>

                                        <span class="text">Back  </span>
                                    </button>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

            </form>
        </div>
    </div>

</div>


@section Scripts{
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons   lists   table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough |  addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent ',
            tinycomments_mode: 'embedded',
            tinycomments_author: 'Author name',
            max_height: 300,
            toolbar: false,


        });
    </script>
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
}